// Package openapi_service provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.10.1 DO NOT EDIT.
package openapi_service

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/5RUT2/TThD9Kj/NjwNIJk5axGFvCCRU9UBFj1WEFnvsbLF3t7vjUiuKVLUqUg5VOZUr",
	"p4L4c6IHDsCXCa7yMdCukzTBSSQu9mp35r19M2+2D5HKtZIoyQLrg416mHO/fIq0K9IePeaEqTIC7XO0",
	"WkmL7lQbpdGQwDrNBb6IZpFuTxDmfnHHYAIM/g9vqcIJTzjPUMIgACo1AgNuDC9hMAjA4EEhDMbA9po0",
	"3VmCermPETmERcjGVUXsvjHayAhNQklgIOK7O9v3IAA84rnOEFgngESZnBMwKISkhw9gRiUkYYrGcUme",
	"YxOuenteDc/n4WB89a06G95c/hx//HqLZMkImTZkihgm0E19LhaPCI3k2RMV2Sb77muepmiqsy/VjwsI",
	"oDAZMOgRaRaGtj5sCeWuL2SiHECkJPGI3LJWBFxKVeaqsC5sEd96Tf892tlyQgR5ffXmfVcak/AIIYBD",
	"NLbO6LTaDkZplFwLYLDZarc2IADNqecVhK+4NCJcZqMUqamxLmf1/vpmeDw6+Tw6fTM6uR6dfvr9/Xh8",
	"9aG6uKx+vQPPaLhL2YqBLTG0v4LhORIaC2yvD8KhHxRoymkLWP0LJqOxptuNpi6HU0likRYAZ1Zb5bRV",
	"WJnIxb9CdZ3Z6kH2Bd5ot6ceQOlrzbXOROQLF+5bJ7I/x7BunNe8Gd65i5V7tu2tb4s8525UV7bVyeCp",
	"bTwBJXQ9rEVzOO3gIkWmIp71lKW/B2F2wDqbG5vhYSeEQXfwJwAA//96hDcqDwUAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
