// Package openapi_service provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.10.1 DO NOT EDIT.
package openapi_service

// GetSightCategoriesResponse defines model for GetSightCategoriesResponse.
type GetSightCategoriesResponse struct {
	SightCategories []SightCategory `json:"sight_categories"`
}

// SightCategory defines model for SightCategory.
type SightCategory struct {
	// id(PK)
	Id uint64 `json:"id"`

	// 名前
	Name string `json:"name"`
}

// GetSightCategoriesParams defines parameters for GetSightCategories.
type GetSightCategoriesParams struct {
	Name   *string `json:"name,omitempty"`
	Offset *int64  `json:"offset,omitempty"`
	Limit  *int64  `json:"limit,omitempty"`
}
