// Package openapi_service provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.11.0 DO NOT EDIT.
package openapi_service

import (
	"time"

	openapi_types "github.com/deepmap/oapi-codegen/pkg/types"
)

const (
	BearerScopes = "Bearer.Scopes"
)

// Defines values for CustomerGender.
const (
	CustomerGenderFemale  CustomerGender = "female"
	CustomerGenderMale    CustomerGender = "male"
	CustomerGenderUnknown CustomerGender = "unknown"
)

// Defines values for CustomerGeneration.
const (
	CustomerGenerationS10     CustomerGeneration = "s10"
	CustomerGenerationS20     CustomerGeneration = "s20"
	CustomerGenerationS30     CustomerGeneration = "s30"
	CustomerGenerationS40     CustomerGeneration = "s40"
	CustomerGenerationS50     CustomerGeneration = "s50"
	CustomerGenerationS60     CustomerGeneration = "s60"
	CustomerGenerationS70     CustomerGeneration = "s70"
	CustomerGenerationS80     CustomerGeneration = "s80"
	CustomerGenerationS90     CustomerGeneration = "s90"
	CustomerGenerationUnknown CustomerGeneration = "Unknown"
)

// Defines values for CustomerPostCustomersRequestBodyGender.
const (
	CustomerPostCustomersRequestBodyGenderFemale  CustomerPostCustomersRequestBodyGender = "female"
	CustomerPostCustomersRequestBodyGenderMale    CustomerPostCustomersRequestBodyGender = "male"
	CustomerPostCustomersRequestBodyGenderUnknown CustomerPostCustomersRequestBodyGender = "unknown"
)

// Defines values for CustomerPostCustomersRequestBodyGeneration.
const (
	CustomerPostCustomersRequestBodyGenerationS10     CustomerPostCustomersRequestBodyGeneration = "s10"
	CustomerPostCustomersRequestBodyGenerationS20     CustomerPostCustomersRequestBodyGeneration = "s20"
	CustomerPostCustomersRequestBodyGenerationS30     CustomerPostCustomersRequestBodyGeneration = "s30"
	CustomerPostCustomersRequestBodyGenerationS40     CustomerPostCustomersRequestBodyGeneration = "s40"
	CustomerPostCustomersRequestBodyGenerationS50     CustomerPostCustomersRequestBodyGeneration = "s50"
	CustomerPostCustomersRequestBodyGenerationS60     CustomerPostCustomersRequestBodyGeneration = "s60"
	CustomerPostCustomersRequestBodyGenerationS70     CustomerPostCustomersRequestBodyGeneration = "s70"
	CustomerPostCustomersRequestBodyGenerationS80     CustomerPostCustomersRequestBodyGeneration = "s80"
	CustomerPostCustomersRequestBodyGenerationS90     CustomerPostCustomersRequestBodyGeneration = "s90"
	CustomerPostCustomersRequestBodyGenerationUnknown CustomerPostCustomersRequestBodyGeneration = "Unknown"
)

// Defines values for OperatorBelong.
const (
	OperatorBelongExternal OperatorBelong = "external"
	OperatorBelongInternal OperatorBelong = "internal"
	OperatorBelongUnknown  OperatorBelong = "unknown"
)

// Defines values for OperatorLevel.
const (
	OperatorLevelNormal  OperatorLevel = "normal"
	OperatorLevelUnknown OperatorLevel = "unknown"
)

// Defines values for OperatorPostOperatorsRequestBodyBelong.
const (
	OperatorPostOperatorsRequestBodyBelongExternal OperatorPostOperatorsRequestBodyBelong = "external"
	OperatorPostOperatorsRequestBodyBelongInternal OperatorPostOperatorsRequestBodyBelong = "internal"
	OperatorPostOperatorsRequestBodyBelongUnknown  OperatorPostOperatorsRequestBodyBelong = "unknown"
)

// Defines values for OperatorPostOperatorsRequestBodyLevel.
const (
	OperatorPostOperatorsRequestBodyLevelNormal  OperatorPostOperatorsRequestBodyLevel = "normal"
	OperatorPostOperatorsRequestBodyLevelUnknown OperatorPostOperatorsRequestBodyLevel = "unknown"
)

// Customer defines model for Customer.
type Customer struct {
	// 自分のプラン公開是非
	AllowPlansDisplayed *bool `json:"allow_plans_displayed,omitempty"`

	// 誕生日
	Birthday *string `json:"birthday,omitempty"`

	// 表示用ユーザー名。
	DisplayName *string `json:"display_name,omitempty"`

	// メールアドレス
	Email *string `json:"email,omitempty"`

	// 性別
	Gender *CustomerGender `json:"gender,omitempty"`

	// 世代
	Generation *CustomerGeneration `json:"generation,omitempty"`

	// 自己紹介
	Introduction *string `json:"introduction,omitempty"`

	// 最終アクセス日
	LastAccessedAt *time.Time `json:"last_accessed_at,omitempty"`

	// 最終ログイン日
	LastLoggedInAt *time.Time `json:"last_logged_in_at,omitempty"`

	// ユーザ名
	Name *string `json:"name,omitempty"`

	// 電話番号
	PhoneNumber *string `json:"phone_number,omitempty"`
}

// 性別
type CustomerGender string

// 世代
type CustomerGeneration string

// CustomerGetSightCategoriesResponse defines model for CustomerGetSightCategoriesResponse.
type CustomerGetSightCategoriesResponse struct {
	SightCategories []SightCategory `json:"sight_categories"`
}

// CustomerGetSightGenresResponse defines model for CustomerGetSightGenresResponse.
type CustomerGetSightGenresResponse struct {
	SightGenres []SightGenre `json:"sight_genres"`
}

// CustomerPostCustomersRequestBody defines model for CustomerPostCustomersRequestBody.
type CustomerPostCustomersRequestBody struct {
	// 自分のプラン公開是非
	AllowPlansDisplayed bool `json:"allow_plans_displayed"`

	// 誕生日
	Birthday openapi_types.Date `json:"birthday"`

	// 表示用ユーザー名。
	DisplayName string `json:"display_name"`

	// メールアドレス
	Email string `json:"email"`

	// 性別
	Gender CustomerPostCustomersRequestBodyGender `json:"gender"`

	// 世代
	Generation CustomerPostCustomersRequestBodyGeneration `json:"generation"`

	// プロフィール画像
	ImageUrl *string `json:"image_url,omitempty"`

	// 自己紹介
	Introduction string `json:"introduction"`

	// ユーザ名
	Name string `json:"name"`

	// パスワード
	Password string `json:"password"`

	// パスワード確認用
	PasswordConfirmation string `json:"password_confirmation"`

	// 電話番号
	PhoneNumber string `json:"phone_number"`
}

// 性別
type CustomerPostCustomersRequestBodyGender string

// 世代
type CustomerPostCustomersRequestBodyGeneration string

// CustomerPostCustomersResponse defines model for CustomerPostCustomersResponse.
type CustomerPostCustomersResponse struct {
	// customer new ID
	Id uint64 `json:"id"`
}

// CustomerPostCustomersSignInRequestBody defines model for CustomerPostCustomersSignInRequestBody.
type CustomerPostCustomersSignInRequestBody struct {
	// メールアドレス
	Email string `json:"email"`

	// パスワード
	Password string `json:"password"`
}

// CustomerPostCustomersSignInResponse defines model for CustomerPostCustomersSignInResponse.
type CustomerPostCustomersSignInResponse struct {
	Customer *Customer `json:"customer,omitempty"`

	// token
	Token *string `json:"token,omitempty"`
}

// Operator defines model for Operator.
type Operator struct {
	// 所属
	Belong *OperatorBelong `json:"belong,omitempty"`

	// 表示用ユーザー名。
	DisplayName *string `json:"display_name,omitempty"`

	// メールアドレス
	Email *string `json:"email,omitempty"`

	// 神権限
	IsGod *bool `json:"is_god,omitempty"`

	// 最終アクセス日
	LastAccessedAt *time.Time `json:"last_accessed_at,omitempty"`

	// 最終ログイン日
	LastLoggedInAt *time.Time `json:"last_logged_in_at,omitempty"`

	// 権限レベル
	Level *OperatorLevel `json:"level,omitempty"`

	// ユーザ名
	Name *string `json:"name,omitempty"`
}

// 所属
type OperatorBelong string

// 権限レベル
type OperatorLevel string

// OperatorGetSightCategoriesResponse defines model for OperatorGetSightCategoriesResponse.
type OperatorGetSightCategoriesResponse struct {
	SightCategories []SightCategory `json:"sight_categories"`
}

// OperatorGetSightGenresResponse defines model for OperatorGetSightGenresResponse.
type OperatorGetSightGenresResponse struct {
	SightGenres []SightGenre `json:"sight_genres"`
}

// OperatorPostOperatorsRequestBody defines model for OperatorPostOperatorsRequestBody.
type OperatorPostOperatorsRequestBody struct {
	// 所属
	Belong OperatorPostOperatorsRequestBodyBelong `json:"belong"`

	// 表示用ユーザー名。
	DisplayName string `json:"display_name"`

	// メールアドレス
	Email string `json:"email"`

	// 神権限有無
	IsGod bool `json:"is_god"`

	// 権限レベル
	Level OperatorPostOperatorsRequestBodyLevel `json:"level"`

	// ユーザ名
	Name string `json:"name"`

	// パスワード
	Password string `json:"password"`

	// パスワード確認用
	PasswordConfirmation string `json:"password_confirmation"`
}

// 所属
type OperatorPostOperatorsRequestBodyBelong string

// 権限レベル
type OperatorPostOperatorsRequestBodyLevel string

// OperatorPostOperatorsResponse defines model for OperatorPostOperatorsResponse.
type OperatorPostOperatorsResponse struct {
	// operator new ID
	Id uint64 `json:"id"`
}

// OperatorPostOperatorsSignInRequestBody defines model for OperatorPostOperatorsSignInRequestBody.
type OperatorPostOperatorsSignInRequestBody struct {
	// メールアドレス
	Email string `json:"email"`

	// パスワード
	Password string `json:"password"`
}

// OperatorPostOperatorsSignInResponse defines model for OperatorPostOperatorsSignInResponse.
type OperatorPostOperatorsSignInResponse struct {
	Operator *Operator `json:"operator,omitempty"`

	// token
	Token *string `json:"token,omitempty"`
}

// SightCategory defines model for SightCategory.
type SightCategory struct {
	// id(PK)
	Id uint64 `json:"id"`

	// 名前
	Name string `json:"name"`
}

// SightGenre defines model for SightGenre.
type SightGenre struct {
	// id(PK)
	Id uint64 `json:"id"`

	// image url
	ImageUrl string `json:"image_url"`

	// 名前
	Name          string        `json:"name"`
	SightCategory SightCategory `json:"sight_category"`
}

// OperatorGetSightCategoriesParams defines parameters for OperatorGetSightCategories.
type OperatorGetSightCategoriesParams struct {
	Name   *string `form:"name,omitempty" json:"name,omitempty"`
	Offset *int64  `form:"offset,omitempty" json:"offset,omitempty"`
	Limit  *int64  `form:"limit,omitempty" json:"limit,omitempty"`
}

// OperatorGetSightGenresParams defines parameters for OperatorGetSightGenres.
type OperatorGetSightGenresParams struct {
	Name            *string `form:"name,omitempty" json:"name,omitempty"`
	SightCategoryId *int64  `form:"sight_category_id,omitempty" json:"sight_category_id,omitempty"`
	Offset          *int64  `form:"offset,omitempty" json:"offset,omitempty"`
	Limit           *int64  `form:"limit,omitempty" json:"limit,omitempty"`
}

// OperatorPostOperatorsSignInJSONBody defines parameters for OperatorPostOperatorsSignIn.
type OperatorPostOperatorsSignInJSONBody = OperatorPostOperatorsSignInRequestBody

// OperatorPostOperatorsJSONBody defines parameters for OperatorPostOperators.
type OperatorPostOperatorsJSONBody = OperatorPostOperatorsRequestBody

// CustomerGetSightCategoriesParams defines parameters for CustomerGetSightCategories.
type CustomerGetSightCategoriesParams struct {
	Name   *string `form:"name,omitempty" json:"name,omitempty"`
	Offset *int64  `form:"offset,omitempty" json:"offset,omitempty"`
	Limit  *int64  `form:"limit,omitempty" json:"limit,omitempty"`
}

// CustomerGetSightGenresParams defines parameters for CustomerGetSightGenres.
type CustomerGetSightGenresParams struct {
	Name            *string `form:"name,omitempty" json:"name,omitempty"`
	SightCategoryId *int64  `form:"sight_category_id,omitempty" json:"sight_category_id,omitempty"`
	Offset          *int64  `form:"offset,omitempty" json:"offset,omitempty"`
	Limit           *int64  `form:"limit,omitempty" json:"limit,omitempty"`
}

// CustomerPostCustomersSignInJSONBody defines parameters for CustomerPostCustomersSignIn.
type CustomerPostCustomersSignInJSONBody = CustomerPostCustomersSignInRequestBody

// CustomerPostCustomersJSONBody defines parameters for CustomerPostCustomers.
type CustomerPostCustomersJSONBody = CustomerPostCustomersRequestBody

// OperatorPostOperatorsSignInJSONRequestBody defines body for OperatorPostOperatorsSignIn for application/json ContentType.
type OperatorPostOperatorsSignInJSONRequestBody = OperatorPostOperatorsSignInJSONBody

// OperatorPostOperatorsJSONRequestBody defines body for OperatorPostOperators for application/json ContentType.
type OperatorPostOperatorsJSONRequestBody = OperatorPostOperatorsJSONBody

// CustomerPostCustomersSignInJSONRequestBody defines body for CustomerPostCustomersSignIn for application/json ContentType.
type CustomerPostCustomersSignInJSONRequestBody = CustomerPostCustomersSignInJSONBody

// CustomerPostCustomersJSONRequestBody defines body for CustomerPostCustomers for application/json ContentType.
type CustomerPostCustomersJSONRequestBody = CustomerPostCustomersJSONBody
