name: staging CI
on:
  push:
    branches:
      - staging
    paths-ignore:
      - '**.md'
      - docs/*
      - .gitignore

jobs:
#  setup:
#  lint:
#  err-check:
#  release:
#    name: build & push image
#    runs-on: ubuntu-latest
#    steps:
#      - name: src checkout
#        id: checkout
#        uses: actions/checkout@v2
#        with:
#          fetch-depth: 1
#
#      - name: check credentials
#        uses: aws-actions/configure-aws-credentials@v1
#        with:
#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_STG }}
#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_STG }}
#          aws-region: ap-northeast-1
#
#      - name: sign in ECR
#        id: ecr_sign_in
#        uses: aws-actions/amazon-ecr-login@v1
#
#      - name: build & tag & push image
#        env:
#          IMAGE_TAG: ${{ github.sha }}
#          ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
#          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
#        run: |
#          docker build -t $ECR_REPOSITORY:$IMAGE_TAG -f build/app/Dockerfile .
#          docker tag $ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
#          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
#
#          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest
#          aws ecr batch-delete-image-image --repository-name $ECR_REPOSITORY --image-ids imageTag=latest
#          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest


